name: Reforca

on:
  push:
    branches-ignore: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Check Commit Type
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '[A-Z]{2,}-\d+'
        error: 'A mensagem necessita conter a issue que o commit pertence.'
    - name: Print commit message
      run: echo ${{ github.event.head_commit.message }} | grep -P '[A-Z]{2,}-\d+' -o
    # Change issues on Jira
    - name: Login on Jira
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ github.event.head_commit.message }} | grep -P '[A-Z]{2,}-\d+' -o
        transition: "In Progress"