name: Reforca

on:
  push:
    branches-ignore: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    # Check and set Jira Issue
    - name: Check Jira Issue in message
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '[A-Z]{2,}-\d+'
        error: 'A mensagem necessita conter a issue que o commit pertence.'
    - name: Check Jira Status in message
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '[A-Z]{2,}-\d+'
        error: 'A mensagem necessita conter a issue que o commit pertence.'
    - name: Set env
      run: echo "ISSUE=$(echo ${{ github.event.head_commit.message }} | grep -P '[A-Z]{2,}-\d+' -o)" >> $GITHUB_ENV
    - name: Test
      run: echo $ISSUE
    # Change Jira Issue
    - name: Login on Jira
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ env.ISSUE }}
        transition: "Pronto para testes"
    # Logs on Slack
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: alertas
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_TITLE: Mensagem do commit
        SLACK_MESSAGE: ${{ github.event.head_commit.message }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}