name: Reforca

on:
  push:
    branches-ignore: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Check Commit Type
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '[A-Z]{2,}-\d+'
        error: 'A mensagem necessita conter a issue que o commit pertence.'
    - name: Print commit message
      run: echo ${{ github.event.head_commit.message }}